const colors = {
  neutral: {
    0: "var(--color-neutral-0)",
    50: "var(--color-neutral-50)",
    100: "var(--color-neutral-100)",
    200: "var(--color-neutral-200)",
    300: "var(--color-neutral-300)",
    400: "var(--color-neutral-400)",
    500: "var(--color-neutral-500)",
    600: "var(--color-neutral-600)",
    700: "var(--color-neutral-700)",
    800: "var(--color-neutral-800)",
    900: "var(--color-neutral-900)",
    950: "var(--color-neutral-950)",
  },
  "neutral-alpha": {
    0: "var(--color-neutral-alpha-0)",
    1: "var(--color-neutral-alpha-1)",
    2: "var(--color-neutral-alpha-2)",
    3: "var(--color-neutral-alpha-3)",
    4: "var(--color-neutral-alpha-4)",
    5: "var(--color-neutral-alpha-5)",
    6: "var(--color-neutral-alpha-6)",
    7: "var(--color-neutral-alpha-7)",
    8: "var(--color-neutral-alpha-8)",
    9: "var(--color-neutral-alpha-9)",
    10: "var(--color-neutral-alpha-10)",
    11: "var(--color-neutral-alpha-11)",
    12: "var(--color-neutral-alpha-12)",
    13: "var(--color-neutral-alpha-13)",
    14: "var(--color-neutral-alpha-14)",
    15: "var(--color-neutral-alpha-15)",
    16: "var(--color-neutral-alpha-16)",
  },
  "neutral-inverted": {
    0: "var(--color-neutral-inverted-0)",
    1: "var(--color-neutral-inverted-1)",
    2: "var(--color-neutral-inverted-2)",
    3: "var(--color-neutral-inverted-3)",
    4: "var(--color-neutral-inverted-4)",
    5: "var(--color-neutral-inverted-5)",
    6: "var(--color-neutral-inverted-6)",
    7: "var(--color-neutral-inverted-7)",
    8: "var(--color-neutral-inverted-8)",
    9: "var(--color-neutral-inverted-9)",
    10: "var(--color-neutral-inverted-10)",
    11: "var(--color-neutral-inverted-11)",
    12: "var(--color-neutral-inverted-12)",
    13: "var(--color-neutral-inverted-13)",
    14: "var(--color-neutral-inverted-14)",
    15: "var(--color-neutral-inverted-15)",
    16: "var(--color-neutral-inverted-16)",
  },
  blue: {
    50: "var(--color-blue-50)",
    100: "var(--color-blue-100)",
    200: "var(--color-blue-200)",
    300: "var(--color-blue-300)",
    400: "var(--color-blue-400)",
    500: "var(--color-blue-500)",
    600: "var(--color-blue-600)",
    700: "var(--color-blue-700)",
    800: "var(--color-blue-800)",
    900: "var(--color-blue-900)",
    950: "var(--color-blue-950)",
  },
  green: {
    50: "var(--color-green-50)",
    100: "var(--color-green-100)",
    200: "var(--color-green-200)",
    300: "var(--color-green-300)",
    400: "var(--color-green-400)",
    500: "var(--color-green-500)",
    600: "var(--color-green-600)",
    700: "var(--color-green-700)",
    800: "var(--color-green-800)",
    900: "var(--color-green-900)",
    950: "var(--color-green-950)",
  },
  lime: {
    50: "var(--color-lime-50)",
    100: "var(--color-lime-100)",
    200: "var(--color-lime-200)",
    300: "var(--color-lime-300)",
    400: "var(--color-lime-400)",
    500: "var(--color-lime-500)",
    600: "var(--color-lime-600)",
    700: "var(--color-lime-700)",
    800: "var(--color-lime-800)",
    900: "var(--color-lime-900)",
    950: "var(--color-lime-950)",
  },
  cyan: {
    50: "var(--color-cyan-50)",
    100: "var(--color-cyan-100)",
    200: "var(--color-cyan-200)",
    300: "var(--color-cyan-300)",
    400: "var(--color-cyan-400)",
    500: "var(--color-cyan-500)",
    600: "var(--color-cyan-600)",
    700: "var(--color-cyan-700)",
    800: "var(--color-cyan-800)",
    900: "var(--color-cyan-900)",
    950: "var(--color-cyan-950)",
  },
  orange: {
    50: "var(--color-orange-50)",
    100: "var(--color-orange-100)",
    200: "var(--color-orange-200)",
    300: "var(--color-orange-300)",
    400: "var(--color-orange-400)",
    500: "var(--color-orange-500)",
    600: "var(--color-orange-600)",
    700: "var(--color-orange-700)",
    800: "var(--color-orange-800)",
    900: "var(--color-orange-900)",
    950: "var(--color-orange-950)",
  },
  red: {
    50: "var(--color-red-50)",
    100: "var(--color-red-100)",
    200: "var(--color-red-200)",
    300: "var(--color-red-300)",
    400: "var(--color-red-400)",
    500: "var(--color-red-500)",
    600: "var(--color-red-600)",
    700: "var(--color-red-700)",
    800: "var(--color-red-800)",
    900: "var(--color-red-900)",
    950: "var(--color-red-950)",
  },
  purple: {
    50: "var(--color-purple-50)",
    100: "var(--color-purple-100)",
    200: "var(--color-purple-200)",
    300: "var(--color-purple-300)",
    400: "var(--color-purple-400)",
    500: "var(--color-purple-500)",
    600: "var(--color-purple-600)",
    700: "var(--color-purple-700)",
    800: "var(--color-purple-800)",
    900: "var(--color-purple-900)",
    950: "var(--color-purple-950)",
  },
  indigo: {
    50: "var(--color-indigo-50)",
    100: "var(--color-indigo-100)",
    200: "var(--color-indigo-200)",
    300: "var(--color-indigo-300)",
    400: "var(--color-indigo-400)",
    500: "var(--color-indigo-500)",
    600: "var(--color-indigo-600)",
    700: "var(--color-indigo-700)",
    800: "var(--color-indigo-800)",
    900: "var(--color-indigo-900)",
    950: "var(--color-indigo-950)",
  },
};

module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      borderRadius: {
        0: 0,
        1: "var(--radius-xs)",
        2: "calc(var(--radius-xs) * 2)",
        3: "calc(var(--radius-xs) * 3)",
        4: "calc(var(--radius-xs) * 4)",
        5: "calc(var(--radius-xs) * 5)",
        6: "calc(var(--radius-xs) * 6)",
        7: "calc(var(--radius-xs) * 8)",
        8: "calc(var(--radius-xs) * 12)",
        9: "calc(var(--radius-xs) * 16)",
        full: 9999,
      },
      colors: {
        ...colors,
        alpha: colors["neutral-alpha"],
        info: {
          DEFAULT: "var(--info)",
          foreground: "var(--info-foreground)",
          ...colors.blue,
        },
        success: {
          DEFAULT: "var(--color-green-600)",
          foreground: "var(--color-green-500)",
          ...colors.lime,
        },
        destructive: {
          DEFAULT: "var(--color-red-600)",
          foreground: "var(--color-red-500)",
          ...colors.red,
        },
        warning: {
          DEFAULT: "var(--color-orange-600)",
          foreground: "var(--color-orange-500)",
          ...colors.orange,
        },
        brand: {
          ...colors.indigo,
        },
        bg: {
          DEFAULT: "var(--background)",
          secondary: "var(--background-secondary)",
        },
        item: {
          primary: {
            DEFAULT: "var(--color-item-primary-primary)",
            hover: "var(--color-item-primary-primary-hover)",
            active: "var(--color-item-primary-primary-active)",
            focus: "var(--color-item-primary-primary-focus)",
          },
          secondary: {
            DEFAULT: "var(--color-item-primary-secondary)",
            hover: "var(--color-item-primary-secondary-hover)",
            active: "var(--color-item-primary-secondary-active)",
          },
          tertiary: {
            DEFAULT: "var(--color-item-primary-tertiary)",
            hover: "var(--color-item-primary-tertiary-hover)",
            active: "var(--color-item-primary-tertiary-active)",
          },
          ghost: {
            DEFAULT: "var(--color-item-primary-ghost)",
            hover: "var(--color-item-primary-ghost-hover)",
            active: "var(--color-item-primary-ghost-active)",
          },
          destructive: {
            DEFAULT: "var(--color-item-primary-destructive)",
            hover: "var(--color-item-primary-destructive-hover)",
            active: "var(--color-item-primary-destructive-active)",
            focus: "var(--color-item-primary-destructive-focus)",
          },
        },
        border: {
          DEFAULT: "var(--border)",
          alpha: {
            strong: "var(--color-border-alpha-strong)",
            light: "var(--color-border-alpha-light)",
            subtle: "var(--color-border-alpha-subtle)",
          },
          light: {
            DEFAULT: "var(--color-border-light)",
          },
        },
        primary: "var(--color-item-primary)",
        secondary: "var(--color-item-secondary)",
        tertiary: "var(--color-item-tertiary)",
        quaternary: "var(--color-item-quaternary)",
        inverted: {
          DEFAULT: "var(--color-item-inverted)",
          secondary: "var(--color-item-inverted-secondary)",
          tertiary: "var(--color-item-inverted-tertiary)",
          quaternary: "var(--color-item-inverted-quaternary)",
        },
        fixed: {
          DEFAULT: "var(--color-item-fixed)",
          secondary: "var(--color-item-fixed-secondary)",
          tertiary: "var(--color-item-fixed-tertiary)",
          quaternary: "var(--color-item-fixed-quaternary)",
          inverted: {
            DEFAULT: "var(--color-item-fixed-inverted)",
            secondary: "var(--color-item-fixed-fixed-inverted-secondary)",
            tertiary: "var(--color-item-fixed-inverted-tertiary)",
            quaternary: "var(--color-item-fixed-inverted-quaternary)",
          },
        },
        surface: {
          base: {
            DEFAULT: "var(--color-surface-base-primary)",
            secondary: "var(--color-surface-base-secondary)",
            tertiary: "var(--color-surface-base-tertiary)",
            inverted: "var(--color-surface-base-inverted)",
          },
          component: {
            DEFAULT: "var(--color-surface-component-primary)",
            secondary: "var(--color-surface-component-secondary)",
            tertiary: "var(--color-surface-component-tertiary)",
          },
          compact: {
            DEFAULT: "var(--color-surface-compact-primary)",
            secondary: "var(--color-surface-compact-secondary)",
            tertiary: "var(--color-surface-compact-tertiary)",
          },
          overlay: "var(--color-surface-overlay)",
          muted: {
            DEFAULT: "var(--color-surface-muted)",
            hover: "var(--color-surface-muted-hover)",
            active: "var(--color-surface-muted-pressed)",
          },
        },
        shadows: {
          inner: {
            DEFAULT: "var(--color-shadows-inner-0)",
            1: "var(--color-shadows-inner-1)",
            2: "var(--color-shadows-inner-2)",
          },
          drop: {
            DEFAULT: "var(--color-shadows-drop-1)",
            2: "var(--color-shadows-drop-2)",
            3: "var(--color-shadows-drop-3)",
            4: "var(--color-shadows-drop-4)",
          },
          highlight: {
            DEFAULT: "var(--color-shadows-highlight-1)",
            2: "var(--color-shadows-highlight-2)",
          },
          danger: {
            DEFAULT: "var(--color-shadows-danger-1)",
            2: "var(--color-shadows-danger-2)",
          },
          card: {
            border: {
              DEFAULT: "var(--color-shadows-card-border)",
              2: "var(--color-shadows-card-border-2)",
            },
          },
        },
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        high: {
          DEFAULT: "var(--high)",
          foreground: "var(--high-foreground)",
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "var(--color-border-light)",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        inter: "var(--font-family-base)",
      },
      fontSize: {
        body: {
          "2xs": {
            light: ["0.688rem", { lineHeight: "1rem", fontWeight: "300" }],
            regular: ["0.688rem", { lineHeight: "1rem", fontWeight: "400" }],
            medium: ["0.688rem", { lineHeight: "1rem", fontWeight: "500" }],
            semiBold: ["0.688rem", { lineHeight: "1rem", fontWeight: "600" }],
            bold: ["0.688rem", { lineHeight: "1rem", fontWeight: "700" }],
            extraBold: ["0.688rem", { lineHeight: "1rem", fontWeight: "800" }],
            black: ["0.688rem", { lineHeight: "1rem", fontWeight: "900" }],
          },
          xs: {
            light: ["0.75rem", { lineHeight: "1.125rem", fontWeight: "300" }],
            regular: ["0.75rem", { lineHeight: "1.125rem", fontWeight: "400" }],
            medium: ["0.75rem", { lineHeight: "1.125rem", fontWeight: "500" }],
            semiBold: [
              "0.75rem",
              { lineHeight: "1.125rem", fontWeight: "600" },
            ],
            bold: ["0.75rem", { lineHeight: "1.125rem", fontWeight: "700" }],
            extraBold: [
              "0.75rem",
              { lineHeight: "1.125rem", fontWeight: "800" },
            ],
            black: ["0.75rem", { lineHeight: "1.125rem", fontWeight: "900" }],
          },
          sm: {
            light: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "300" }],
            regular: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
            medium: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
            semiBold: [
              "0.875rem",
              { lineHeight: "1.25rem", fontWeight: "600" },
            ],
            bold: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "700" }],
            extraBold: [
              "0.875rem",
              { lineHeight: "1.25rem", fontWeight: "800" },
            ],
            black: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "900" }],
          },
          md: {
            light: ["1rem", { lineHeight: "1.5rem", fontWeight: "300" }],
            regular: ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
            medium: ["1rem", { lineHeight: "1.5rem", fontWeight: "500" }],
            semiBold: ["1rem", { lineHeight: "1.5rem", fontWeight: "600" }],
            bold: ["1rem", { lineHeight: "1.5rem", fontWeight: "700" }],
            extraBold: ["1rem", { lineHeight: "1.5rem", fontWeight: "800" }],
            black: ["1rem", { lineHeight: "1.5rem", fontWeight: "900" }],
          },
          lg: {
            light: ["1.125rem", { lineHeight: "1.75rem", fontWeight: "300" }],
            regular: ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
            medium: ["1.125rem", { lineHeight: "1.75rem", fontWeight: "500" }],
            semiBold: [
              "1.125rem",
              { lineHeight: "1.75rem", fontWeight: "600" },
            ],
            bold: ["1.125rem", { lineHeight: "1.75rem", fontWeight: "700" }],
            extraBold: [
              "1.125rem",
              { lineHeight: "1.75rem", fontWeight: "800" },
            ],
            black: ["1.125rem", { lineHeight: "1.75rem", fontWeight: "900" }],
          },
        },
        headline: {
          "2xs": {
            light: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "300" }],
            regular: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "400" }],
            medium: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "500" }],
            semiBold: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
            bold: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "700" }],
            extraBold: [
              "1.25rem",
              { lineHeight: "1.75rem", fontWeight: "800" },
            ],
            black: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "900" }],
          },
          xs: {
            light: ["1.5rem", { lineHeight: "1.875rem", fontWeight: "300" }],
            regular: ["1.5rem", { lineHeight: "1.875rem", fontWeight: "400" }],
            medium: ["1.5rem", { lineHeight: "1.875rem", fontWeight: "500" }],
            semiBold: ["1.5rem", { lineHeight: "1.875rem", fontWeight: "600" }],
            bold: ["1.5rem", { lineHeight: "1.875rem", fontWeight: "700" }],
            extraBold: [
              "1.5rem",
              { lineHeight: "1.875rem", fontWeight: "800" },
            ],
            black: ["1.5rem", { lineHeight: "1.875rem", fontWeight: "900" }],
          },
          sm: {
            light: ["1.75rem", { lineHeight: "2.25rem", fontWeight: "300" }],
            regular: ["1.75rem", { lineHeight: "2.25rem", fontWeight: "400" }],
            medium: ["1.75rem", { lineHeight: "2.25rem", fontWeight: "500" }],
            semiBold: ["1.75rem", { lineHeight: "2.25rem", fontWeight: "600" }],
            bold: ["1.75rem", { lineHeight: "2.25rem", fontWeight: "700" }],
            extraBold: [
              "1.75rem",
              { lineHeight: "2.25rem", fontWeight: "800" },
            ],
            black: ["1.75rem", { lineHeight: "2.25rem", fontWeight: "900" }],
          },
          md: {
            light: ["2.5rem", { lineHeight: "3rem", fontWeight: "300" }],
            regular: ["2.5rem", { lineHeight: "3rem", fontWeight: "400" }],
            medium: ["2.5rem", { lineHeight: "3rem", fontWeight: "500" }],
            semiBold: ["2.5rem", { lineHeight: "3rem", fontWeight: "600" }],
            bold: ["2.5rem", { lineHeight: "3rem", fontWeight: "700" }],
            extraBold: ["2.5rem", { lineHeight: "3rem", fontWeight: "800" }],
            black: ["2.5rem", { lineHeight: "3rem", fontWeight: "900" }],
          },
          lg: {
            light: ["3rem", { lineHeight: "3.5rem", fontWeight: "300" }],
            regular: ["3rem", { lineHeight: "3.5rem", fontWeight: "400" }],
            medium: ["3rem", { lineHeight: "3.5rem", fontWeight: "500" }],
            semiBold: ["3rem", { lineHeight: "3.5rem", fontWeight: "600" }],
            bold: ["3rem", { lineHeight: "3.5rem", fontWeight: "700" }],
            extraBold: ["3rem", { lineHeight: "3.5rem", fontWeight: "800" }],
            black: ["3rem", { lineHeight: "3.5rem", fontWeight: "900" }],
          },
          xl: {
            light: ["4rem", { lineHeight: "4.5rem", fontWeight: "300" }],
            regular: ["4rem", { lineHeight: "4.5rem", fontWeight: "400" }],
            medium: ["4rem", { lineHeight: "4.5rem", fontWeight: "500" }],
            semiBold: ["4rem", { lineHeight: "4.5rem", fontWeight: "600" }],
            bold: ["4rem", { lineHeight: "4.5rem", fontWeight: "700" }],
            extraBold: ["4rem", { lineHeight: "4.5rem", fontWeight: "800" }],
            black: ["4rem", { lineHeight: "4.5rem", fontWeight: "900" }],
          },
          "2xl": {
            light: ["4.5rem", { lineHeight: "5rem", fontWeight: "300" }],
            regular: ["4.5rem", { lineHeight: "5rem", fontWeight: "400" }],
            medium: ["4.5rem", { lineHeight: "5rem", fontWeight: "500" }],
            semiBold: ["4.5rem", { lineHeight: "5rem", fontWeight: "600" }],
            bold: ["4.5rem", { lineHeight: "5rem", fontWeight: "700" }],
            extraBold: ["4.5rem", { lineHeight: "5rem", fontWeight: "800" }],
            black: ["4.5rem", { lineHeight: "5rem", fontWeight: "900" }],
          },
        },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require("tailwind-scrollbar")({
      nocompatible: true,
      preferredStrategy: "pseudoelements",
    }),
  ],
};
